name: CI

on: [push, pull_request]

jobs:
  packages:
    name: check npm install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: setup Node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: check npm ci
        run: npm ci
      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
  lint:
    name: run lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: setup Node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: npm ci
        run: npm ci
      - name: run lint
        run: npm run lint -- --max-warnings=0
  typecheck:
    name: run typecheck
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: setup Node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: npm ci
        run: npm ci
      - name: run typecheck
        run: npm run typecheck
